#!/bin/sh

ENABLED=yes

DESC="qBitTorrent client"
PROCS="qbittorrent-nox"
PROG="/opt/bin/$PROCS"

ARGS="--webui-port=9080 --profile=/opt/etc --configuration=entware -d"
PREARGS=""

. /opt/etc/init.d/rc.func
