#!/bin/sh

ENABLED=yes

DESC="SSDP daemon"
PROCS="minissdpd"
PROG="/opt/sbin/$PROCS"

{ [ -f "/opt/etc/config/$PROCS.conf" ] && . /opt/etc/config/$PROCS.conf ; } || \
{ printf "\033[1;31m %s \033[0m\n" "Abort: conf file not found." && exit 1 ; }

ARGS="-i $INTERFACE"
PREARGS=""

. /opt/etc/init.d/rc.func
