#!/bin/sh

ENABLED=yes

DESC="Open Source Conditional Access Module service"
PROCS="oscam"
PROG="/opt/bin/$PROCS"

pre_cmd() {
  [ -d "/opt/var/log/$PROCS/cw" ] || \
  mkdir -pm 0750 /opt/var/log/"$PROCS"/cw
}

PRECMD="pre_cmd"
ARGS="-b"
PREARGS=""

. /opt/etc/init.d/rc.func
