#!/bin/sh

ENABLED=yes

DESC="VPN server"
PROCS="accel-pppd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "$PID_FILE"
  for i in \
    /opt/var/lib/accel-ppp \
    /opt/var/log/accel-ppp
  do
    [ -d "$i" ] || {
      mkdir -pm 0750 "$i"
    }
  done
}

PRECMD="pre_cmd"
ARGS="-d -c /opt/etc/accel-ppp.conf -p $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
