#!/bin/sh

ENABLED=yes

DESC="Proxy server"
PROCS="3proxy"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "$PID_FILE"
  [ -d "/opt/var/lib/$PROCS" ] || \
  mkdir -pm 0750 /opt/var/lib/"$PROCS"
}

PRECMD="pre_cmd"
ARGS="/opt/etc/$PROCS/$PROCS.cfg"
PREARGS=""

. /opt/etc/init.d/rc.func
