#!/bin/sh

ENABLED=yes

DESC="Policy routing daemon"
PROCS="pingu"
PROG="/opt/sbin/$PROCS"

pre_cmd() {
  rm -f /opt/var/run/$PROCS.ctl
}

PRECMD="pre_cmd"
ARGS="-d"
PREARGS=""

. /opt/etc/init.d/rc.func
