#!/bin/sh

ENABLED=yes

DESC="ShadowSocks local service"
PROCS="ss-local"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "PID_FILE"
}

PRECMD="pre_cmd"
ARGS="-f $PID_FILE -c /opt/etc/shadowsocks.json"
PREARGS=""

. /opt/etc/init.d/rc.func
