#!/bin/sh

ENABLED=yes

DESC="FTP server"
PROCS="vsftpd"
PROG="/opt/sbin/$PROCS"

pre_cmd() {
  [ -d "/opt/var/run/$PROCS" ] || \
  mkdir -pm 0755 /opt/var/run/"$PROCS"
}

PRECMD="pre_cmd"
ARGS=""
PREARGS=""

. /opt/etc/init.d/rc.func
