#!/bin/sh

ENABLED=yes

DESC="AirScan SANE Scanner server"
PROCS="airsaned"
PROG="/opt/bin/$PROCS"

{ [ -f "/opt/etc/config/$PROCS.conf" ] && . /opt/etc/config/$PROCS.conf ; } || \
{ printf "\033[1;31m %s \033[0m\n" "Abort: conf file not found." && exit 1 ; }

ARGS="\
--interface=${INTERFACE} \
--listen-port=${LISTEN_PORT} \
--access-log=${ACCESS_LOG} \
--hotplug=${HOTPLUG} \
--mdns-announce=${MDNS_ANNOUNCE} \
--local-scanners-only=${LOCAL_SCANNERS_ONLY} \
--options-file=${OPTIONS_FILE} \
--ignore-list=${IGNORE_LIST}"
PREARGS=""

. /opt/etc/init.d/rc.func
