#!/bin/sh

ENABLED=yes

DESC="Multi Stream daemon"
PROCS="msd"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "PID_FILE"
}

PRECMD="pre_cmd"
ARGS="-d -c /opt/etc/$PROCS.conf -p $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
