#!/bin/sh

ENABLED=yes

DESC="Network Traffic Monitor"
PROCS="ntopng"
PROG="/opt/bin/$PROCS"

LIMIT="20"
PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "$PID_FILE"
  [ -d "/opt/var/lib/$PROCS" ] || \
  mkdir -pm 0750 /opt/var/lib/"$PROCS"
}

PRECMD="pre_cmd"
ARGS="/opt/etc/$PROCS/$PROCS.conf"
PREARGS=""

. /opt/etc/init.d/rc.func
