#!/bin/sh

ENABLED=yes

DESC="BitTorrent (cfp) client"
PROCS="transmission-daemon"
PROG="/opt/bin/$PROCS"

TRANSMISSION_WEB_HOME="/opt/share/transmission/web"

ARGS="-g /opt/etc/transmission"
PREARGS=""

. /opt/etc/init.d/rc.func
