#!/bin/sh

ENABLED=yes

DESC="DNS proxy and translator for IPv4/6"
PROCS="totd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "PID_FILE"
}

PRECMD="pre_cmd"
ARGS=""
PREARGS=""

. /opt/etc/init.d/rc.func
